/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#131314",
        "on-secondary-container": "#5b3800",
        "secondary-container": "#ee9800",
        "on-primary-container": "#00574d",
        "primary-container": "#2dd4bf",
        "on-tertiary-container": "#4d4c4f",
        "inverse-on-surface": "#313031",
        "surface-container-high": "#2a2a2b",
        "secondary-fixed-dim": "#ffb95f",
        "tertiary-container": "#c0bdc0",
        "tertiary-fixed-dim": "#c8c6c8",
        "on-secondary-fixed": "#2a1700",
        "surface-container-highest": "#353436",
        "primary-fixed": "#62fae3",
        tertiary: "#dcd9db",
        "on-secondary": "#472a00",
        "surface-container-low": "#1c1b1c",
        "on-tertiary-fixed-variant": "#474649",
        "on-primary-fixed": "#00201c",
        "outline-variant": "#3c4a46",
        "on-primary-fixed-variant": "#005047",
        "inverse-surface": "#e5e2e3",
        "surface-tint": "#3cddc7",
        primary: "#57f1db",
        "on-tertiary": "#303032",
        "error-container": "#93000a",
        secondary: "#ffb95f",
        "surface-bright": "#3a393a",
        "on-error": "#690005",
        "surface-dim": "#131314",
        "surface-container-lowest": "#0e0e0f",
        "on-surface": "#e5e2e3",
        "inverse-primary": "#006b5f",
        "on-tertiary-fixed": "#1b1b1d",
        "surface-container": "#201f20",
        "surface-variant": "#353436",
        outline: "#859490",
        "on-primary": "#003731",
        "primary-fixed-dim": "#3cddc7",
        background: "#131314",
        "secondary-fixed": "#ffddb8",
        "on-secondary-fixed-variant": "#653e00",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#e5e1e4",
        "on-surface-variant": "#bacac5",
        "on-background": "#e5e2e3",
        error: "#ffb4ab",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
